/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppArchivadosRouteImport } from './routes/_app/archivados'
import { Route as AppBandejaRouteImport } from './routes/_app/bandeja'
import { Route as AppCalendarioRouteImport } from './routes/_app/calendario'
import { Route as AppCamposPersonalizadosRouteImport } from './routes/_app/campos-personalizados'
import { Route as AppCompartirRouteImport } from './routes/_app/compartir'
import { Route as AppEquipoRouteRouteImport } from './routes/_app/equipo/route'
import { Route as AppEspaciosRouteImport } from './routes/_app/espacios'
import { Route as AppMembersRouteImport } from './routes/_app/members'
import { Route as AppMisTareasRouteImport } from './routes/_app/mis-tareas'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppPlantillasRouteImport } from './routes/_app/plantillas'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppReportesRouteImport } from './routes/_app/reportes'
import { Route as AppTablaRouteImport } from './routes/_app/tabla'
import { Route as AppTimelineRouteImport } from './routes/_app/timeline'
import { Route as EnlaceTokenRouteImport } from './routes/enlace.$token'
import { Route as AppEquipoIndexRouteImport } from './routes/_app/equipo/index'
import { Route as AppEquipoEquiposRouteImport } from './routes/_app/equipo/equipos'
import { Route as AppEquipoOrganigramaRouteImport } from './routes/_app/equipo/organigrama'
import { Route as AppEquipoPersonasRouteImport } from './routes/_app/equipo/personas'
import { Route as AppFFolderIdRouteImport } from './routes/_app/f.$folderId'
import { Route as AppPProjectIdRouteRouteImport } from './routes/_app/p.$projectId/route'
import { Route as AppPProjectIdBoardRouteImport } from './routes/_app/p.$projectId/board'
import { Route as AppPProjectIdCalendarRouteImport } from './routes/_app/p.$projectId/calendar'
import { Route as AppPProjectIdGanttRouteImport } from './routes/_app/p.$projectId/gantt'
import { Route as AppPProjectIdListRouteImport } from './routes/_app/p.$projectId/list'
import { Route as AppPProjectIdSummaryRouteImport } from './routes/_app/p.$projectId/summary'
import { Route as AppPProjectIdTableRouteImport } from './routes/_app/p.$projectId/table'
import { Route as AppPProjectIdTTaskIdRouteImport } from './routes/_app/p.$projectId/t.$taskId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArchivadosRoute = AppArchivadosRouteImport.update({
  id: '/archivados',
  path: '/archivados',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBandejaRoute = AppBandejaRouteImport.update({
  id: '/bandeja',
  path: '/bandeja',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCamposPersonalizadosRoute = AppCamposPersonalizadosRouteImport.update({
  id: '/campos-personalizados',
  path: '/campos-personalizados',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCompartirRoute = AppCompartirRouteImport.update({
  id: '/compartir',
  path: '/compartir',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEquipoRouteRoute = AppEquipoRouteRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEspaciosRoute = AppEspaciosRouteImport.update({
  id: '/espacios',
  path: '/espacios',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMisTareasRoute = AppMisTareasRouteImport.update({
  id: '/mis-tareas',
  path: '/mis-tareas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlantillasRoute = AppPlantillasRouteImport.update({
  id: '/plantillas',
  path: '/plantillas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportesRoute = AppReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTablaRoute = AppTablaRouteImport.update({
  id: '/tabla',
  path: '/tabla',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRouteRoute,
} as any)
const EnlaceTokenRoute = EnlaceTokenRouteImport.update({
  id: '/enlace/$token',
  path: '/enlace/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEquipoIndexRoute = AppEquipoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEquipoRouteRoute,
} as any)
const AppEquipoEquiposRoute = AppEquipoEquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => AppEquipoRouteRoute,
} as any)
const AppEquipoOrganigramaRoute = AppEquipoOrganigramaRouteImport.update({
  id: '/organigrama',
  path: '/organigrama',
  getParentRoute: () => AppEquipoRouteRoute,
} as any)
const AppEquipoPersonasRoute = AppEquipoPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AppEquipoRouteRoute,
} as any)
const AppFFolderIdRoute = AppFFolderIdRouteImport.update({
  id: '/f/$folderId',
  path: '/f/$folderId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPProjectIdRouteRoute = AppPProjectIdRouteRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPProjectIdBoardRoute = AppPProjectIdBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppPProjectIdRouteRoute,
} as any)
const AppPProjectIdCalendarRoute = AppPProjectIdCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppPProjectIdRouteRoute,
} as any)
const AppPProjectIdGanttRoute = AppPProjectIdGanttRouteImport.update({
  id: '/gantt',
  path: '/gantt',
  getParentRoute: () => AppPProjectIdRouteRoute,
} as any)
const AppPProjectIdListRoute = AppPProjectIdListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AppPProjectIdRouteRoute,
} as any)
const AppPProjectIdSummaryRoute = AppPProjectIdSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AppPProjectIdRouteRoute,
} as any)
const AppPProjectIdTableRoute = AppPProjectIdTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => AppPProjectIdRouteRoute,
} as any)
const AppPProjectIdTTaskIdRoute = AppPProjectIdTTaskIdRouteImport.update({
  id: '/t/$taskId',
  path: '/t/$taskId',
  getParentRoute: () => AppPProjectIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/equipo': typeof AppEquipoRouteRouteWithChildren
  '/admin': typeof AppAdminRoute
  '/archivados': typeof AppArchivadosRoute
  '/bandeja': typeof AppBandejaRoute
  '/calendario': typeof AppCalendarioRoute
  '/campos-personalizados': typeof AppCamposPersonalizadosRoute
  '/compartir': typeof AppCompartirRoute
  '/espacios': typeof AppEspaciosRoute
  '/members': typeof AppMembersRoute
  '/mis-tareas': typeof AppMisTareasRoute
  '/onboarding': typeof AppOnboardingRoute
  '/plantillas': typeof AppPlantillasRoute
  '/profile': typeof AppProfileRoute
  '/reportes': typeof AppReportesRoute
  '/tabla': typeof AppTablaRoute
  '/timeline': typeof AppTimelineRoute
  '/enlace/$token': typeof EnlaceTokenRoute
  '/p/$projectId': typeof AppPProjectIdRouteRouteWithChildren
  '/equipo/equipos': typeof AppEquipoEquiposRoute
  '/equipo/organigrama': typeof AppEquipoOrganigramaRoute
  '/equipo/personas': typeof AppEquipoPersonasRoute
  '/f/$folderId': typeof AppFFolderIdRoute
  '/equipo/': typeof AppEquipoIndexRoute
  '/p/$projectId/board': typeof AppPProjectIdBoardRoute
  '/p/$projectId/calendar': typeof AppPProjectIdCalendarRoute
  '/p/$projectId/gantt': typeof AppPProjectIdGanttRoute
  '/p/$projectId/list': typeof AppPProjectIdListRoute
  '/p/$projectId/summary': typeof AppPProjectIdSummaryRoute
  '/p/$projectId/table': typeof AppPProjectIdTableRoute
  '/p/$projectId/t/$taskId': typeof AppPProjectIdTTaskIdRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/archivados': typeof AppArchivadosRoute
  '/bandeja': typeof AppBandejaRoute
  '/calendario': typeof AppCalendarioRoute
  '/campos-personalizados': typeof AppCamposPersonalizadosRoute
  '/compartir': typeof AppCompartirRoute
  '/espacios': typeof AppEspaciosRoute
  '/members': typeof AppMembersRoute
  '/mis-tareas': typeof AppMisTareasRoute
  '/onboarding': typeof AppOnboardingRoute
  '/plantillas': typeof AppPlantillasRoute
  '/profile': typeof AppProfileRoute
  '/reportes': typeof AppReportesRoute
  '/tabla': typeof AppTablaRoute
  '/timeline': typeof AppTimelineRoute
  '/enlace/$token': typeof EnlaceTokenRoute
  '/': typeof AppIndexRoute
  '/p/$projectId': typeof AppPProjectIdRouteRouteWithChildren
  '/equipo/equipos': typeof AppEquipoEquiposRoute
  '/equipo/organigrama': typeof AppEquipoOrganigramaRoute
  '/equipo/personas': typeof AppEquipoPersonasRoute
  '/f/$folderId': typeof AppFFolderIdRoute
  '/equipo': typeof AppEquipoIndexRoute
  '/p/$projectId/board': typeof AppPProjectIdBoardRoute
  '/p/$projectId/calendar': typeof AppPProjectIdCalendarRoute
  '/p/$projectId/gantt': typeof AppPProjectIdGanttRoute
  '/p/$projectId/list': typeof AppPProjectIdListRoute
  '/p/$projectId/summary': typeof AppPProjectIdSummaryRoute
  '/p/$projectId/table': typeof AppPProjectIdTableRoute
  '/p/$projectId/t/$taskId': typeof AppPProjectIdTTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/equipo': typeof AppEquipoRouteRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/archivados': typeof AppArchivadosRoute
  '/_app/bandeja': typeof AppBandejaRoute
  '/_app/calendario': typeof AppCalendarioRoute
  '/_app/campos-personalizados': typeof AppCamposPersonalizadosRoute
  '/_app/compartir': typeof AppCompartirRoute
  '/_app/espacios': typeof AppEspaciosRoute
  '/_app/members': typeof AppMembersRoute
  '/_app/mis-tareas': typeof AppMisTareasRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/plantillas': typeof AppPlantillasRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reportes': typeof AppReportesRoute
  '/_app/tabla': typeof AppTablaRoute
  '/_app/timeline': typeof AppTimelineRoute
  '/enlace/$token': typeof EnlaceTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/p/$projectId': typeof AppPProjectIdRouteRouteWithChildren
  '/_app/equipo/equipos': typeof AppEquipoEquiposRoute
  '/_app/equipo/organigrama': typeof AppEquipoOrganigramaRoute
  '/_app/equipo/personas': typeof AppEquipoPersonasRoute
  '/_app/f/$folderId': typeof AppFFolderIdRoute
  '/_app/equipo/': typeof AppEquipoIndexRoute
  '/_app/p/$projectId/board': typeof AppPProjectIdBoardRoute
  '/_app/p/$projectId/calendar': typeof AppPProjectIdCalendarRoute
  '/_app/p/$projectId/gantt': typeof AppPProjectIdGanttRoute
  '/_app/p/$projectId/list': typeof AppPProjectIdListRoute
  '/_app/p/$projectId/summary': typeof AppPProjectIdSummaryRoute
  '/_app/p/$projectId/table': typeof AppPProjectIdTableRoute
  '/_app/p/$projectId/t/$taskId': typeof AppPProjectIdTTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/reset-password'
    | '/equipo'
    | '/admin'
    | '/archivados'
    | '/bandeja'
    | '/calendario'
    | '/campos-personalizados'
    | '/compartir'
    | '/espacios'
    | '/members'
    | '/mis-tareas'
    | '/onboarding'
    | '/plantillas'
    | '/profile'
    | '/reportes'
    | '/tabla'
    | '/timeline'
    | '/enlace/$token'
    | '/p/$projectId'
    | '/equipo/equipos'
    | '/equipo/organigrama'
    | '/equipo/personas'
    | '/f/$folderId'
    | '/equipo/'
    | '/p/$projectId/board'
    | '/p/$projectId/calendar'
    | '/p/$projectId/gantt'
    | '/p/$projectId/list'
    | '/p/$projectId/summary'
    | '/p/$projectId/table'
    | '/p/$projectId/t/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/archivados'
    | '/bandeja'
    | '/calendario'
    | '/campos-personalizados'
    | '/compartir'
    | '/espacios'
    | '/members'
    | '/mis-tareas'
    | '/onboarding'
    | '/plantillas'
    | '/profile'
    | '/reportes'
    | '/tabla'
    | '/timeline'
    | '/enlace/$token'
    | '/'
    | '/p/$projectId'
    | '/equipo/equipos'
    | '/equipo/organigrama'
    | '/equipo/personas'
    | '/f/$folderId'
    | '/equipo'
    | '/p/$projectId/board'
    | '/p/$projectId/calendar'
    | '/p/$projectId/gantt'
    | '/p/$projectId/list'
    | '/p/$projectId/summary'
    | '/p/$projectId/table'
    | '/p/$projectId/t/$taskId'
  id:
    | '__root__'
    | '/_app'
    | '/accept-invite'
    | '/login'
    | '/reset-password'
    | '/_app/equipo'
    | '/_app/admin'
    | '/_app/archivados'
    | '/_app/bandeja'
    | '/_app/calendario'
    | '/_app/campos-personalizados'
    | '/_app/compartir'
    | '/_app/espacios'
    | '/_app/members'
    | '/_app/mis-tareas'
    | '/_app/onboarding'
    | '/_app/plantillas'
    | '/_app/profile'
    | '/_app/reportes'
    | '/_app/tabla'
    | '/_app/timeline'
    | '/enlace/$token'
    | '/_app/'
    | '/_app/p/$projectId'
    | '/_app/equipo/equipos'
    | '/_app/equipo/organigrama'
    | '/_app/equipo/personas'
    | '/_app/f/$folderId'
    | '/_app/equipo/'
    | '/_app/p/$projectId/board'
    | '/_app/p/$projectId/calendar'
    | '/_app/p/$projectId/gantt'
    | '/_app/p/$projectId/list'
    | '/_app/p/$projectId/summary'
    | '/_app/p/$projectId/table'
    | '/_app/p/$projectId/t/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  EnlaceTokenRoute: typeof EnlaceTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/archivados': {
      id: '/_app/archivados'
      path: '/archivados'
      fullPath: '/archivados'
      preLoaderRoute: typeof AppArchivadosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/bandeja': {
      id: '/_app/bandeja'
      path: '/bandeja'
      fullPath: '/bandeja'
      preLoaderRoute: typeof AppBandejaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/calendario': {
      id: '/_app/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/campos-personalizados': {
      id: '/_app/campos-personalizados'
      path: '/campos-personalizados'
      fullPath: '/campos-personalizados'
      preLoaderRoute: typeof AppCamposPersonalizadosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/compartir': {
      id: '/_app/compartir'
      path: '/compartir'
      fullPath: '/compartir'
      preLoaderRoute: typeof AppCompartirRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/equipo': {
      id: '/_app/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof AppEquipoRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/espacios': {
      id: '/_app/espacios'
      path: '/espacios'
      fullPath: '/espacios'
      preLoaderRoute: typeof AppEspaciosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/mis-tareas': {
      id: '/_app/mis-tareas'
      path: '/mis-tareas'
      fullPath: '/mis-tareas'
      preLoaderRoute: typeof AppMisTareasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/plantillas': {
      id: '/_app/plantillas'
      path: '/plantillas'
      fullPath: '/plantillas'
      preLoaderRoute: typeof AppPlantillasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reportes': {
      id: '/_app/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AppReportesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tabla': {
      id: '/_app/tabla'
      path: '/tabla'
      fullPath: '/tabla'
      preLoaderRoute: typeof AppTablaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/timeline': {
      id: '/_app/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/enlace/$token': {
      id: '/enlace/$token'
      path: '/enlace/$token'
      fullPath: '/enlace/$token'
      preLoaderRoute: typeof EnlaceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/equipo/': {
      id: '/_app/equipo/'
      path: '/'
      fullPath: '/equipo/'
      preLoaderRoute: typeof AppEquipoIndexRouteImport
      parentRoute: typeof AppEquipoRouteRoute
    }
    '/_app/equipo/equipos': {
      id: '/_app/equipo/equipos'
      path: '/equipos'
      fullPath: '/equipo/equipos'
      preLoaderRoute: typeof AppEquipoEquiposRouteImport
      parentRoute: typeof AppEquipoRouteRoute
    }
    '/_app/equipo/organigrama': {
      id: '/_app/equipo/organigrama'
      path: '/organigrama'
      fullPath: '/equipo/organigrama'
      preLoaderRoute: typeof AppEquipoOrganigramaRouteImport
      parentRoute: typeof AppEquipoRouteRoute
    }
    '/_app/equipo/personas': {
      id: '/_app/equipo/personas'
      path: '/personas'
      fullPath: '/equipo/personas'
      preLoaderRoute: typeof AppEquipoPersonasRouteImport
      parentRoute: typeof AppEquipoRouteRoute
    }
    '/_app/f/$folderId': {
      id: '/_app/f/$folderId'
      path: '/f/$folderId'
      fullPath: '/f/$folderId'
      preLoaderRoute: typeof AppFFolderIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/p/$projectId': {
      id: '/_app/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof AppPProjectIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/p/$projectId/board': {
      id: '/_app/p/$projectId/board'
      path: '/board'
      fullPath: '/p/$projectId/board'
      preLoaderRoute: typeof AppPProjectIdBoardRouteImport
      parentRoute: typeof AppPProjectIdRouteRoute
    }
    '/_app/p/$projectId/calendar': {
      id: '/_app/p/$projectId/calendar'
      path: '/calendar'
      fullPath: '/p/$projectId/calendar'
      preLoaderRoute: typeof AppPProjectIdCalendarRouteImport
      parentRoute: typeof AppPProjectIdRouteRoute
    }
    '/_app/p/$projectId/gantt': {
      id: '/_app/p/$projectId/gantt'
      path: '/gantt'
      fullPath: '/p/$projectId/gantt'
      preLoaderRoute: typeof AppPProjectIdGanttRouteImport
      parentRoute: typeof AppPProjectIdRouteRoute
    }
    '/_app/p/$projectId/list': {
      id: '/_app/p/$projectId/list'
      path: '/list'
      fullPath: '/p/$projectId/list'
      preLoaderRoute: typeof AppPProjectIdListRouteImport
      parentRoute: typeof AppPProjectIdRouteRoute
    }
    '/_app/p/$projectId/summary': {
      id: '/_app/p/$projectId/summary'
      path: '/summary'
      fullPath: '/p/$projectId/summary'
      preLoaderRoute: typeof AppPProjectIdSummaryRouteImport
      parentRoute: typeof AppPProjectIdRouteRoute
    }
    '/_app/p/$projectId/table': {
      id: '/_app/p/$projectId/table'
      path: '/table'
      fullPath: '/p/$projectId/table'
      preLoaderRoute: typeof AppPProjectIdTableRouteImport
      parentRoute: typeof AppPProjectIdRouteRoute
    }
    '/_app/p/$projectId/t/$taskId': {
      id: '/_app/p/$projectId/t/$taskId'
      path: '/t/$taskId'
      fullPath: '/p/$projectId/t/$taskId'
      preLoaderRoute: typeof AppPProjectIdTTaskIdRouteImport
      parentRoute: typeof AppPProjectIdRouteRoute
    }
  }
}

interface AppEquipoRouteRouteChildren {
  AppEquipoEquiposRoute: typeof AppEquipoEquiposRoute
  AppEquipoOrganigramaRoute: typeof AppEquipoOrganigramaRoute
  AppEquipoPersonasRoute: typeof AppEquipoPersonasRoute
  AppEquipoIndexRoute: typeof AppEquipoIndexRoute
}

const AppEquipoRouteRouteChildren: AppEquipoRouteRouteChildren = {
  AppEquipoEquiposRoute: AppEquipoEquiposRoute,
  AppEquipoOrganigramaRoute: AppEquipoOrganigramaRoute,
  AppEquipoPersonasRoute: AppEquipoPersonasRoute,
  AppEquipoIndexRoute: AppEquipoIndexRoute,
}

const AppEquipoRouteRouteWithChildren = AppEquipoRouteRoute._addFileChildren(
  AppEquipoRouteRouteChildren,
)

interface AppPProjectIdRouteRouteChildren {
  AppPProjectIdBoardRoute: typeof AppPProjectIdBoardRoute
  AppPProjectIdCalendarRoute: typeof AppPProjectIdCalendarRoute
  AppPProjectIdGanttRoute: typeof AppPProjectIdGanttRoute
  AppPProjectIdListRoute: typeof AppPProjectIdListRoute
  AppPProjectIdSummaryRoute: typeof AppPProjectIdSummaryRoute
  AppPProjectIdTableRoute: typeof AppPProjectIdTableRoute
  AppPProjectIdTTaskIdRoute: typeof AppPProjectIdTTaskIdRoute
}

const AppPProjectIdRouteRouteChildren: AppPProjectIdRouteRouteChildren = {
  AppPProjectIdBoardRoute: AppPProjectIdBoardRoute,
  AppPProjectIdCalendarRoute: AppPProjectIdCalendarRoute,
  AppPProjectIdGanttRoute: AppPProjectIdGanttRoute,
  AppPProjectIdListRoute: AppPProjectIdListRoute,
  AppPProjectIdSummaryRoute: AppPProjectIdSummaryRoute,
  AppPProjectIdTableRoute: AppPProjectIdTableRoute,
  AppPProjectIdTTaskIdRoute: AppPProjectIdTTaskIdRoute,
}

const AppPProjectIdRouteRouteWithChildren =
  AppPProjectIdRouteRoute._addFileChildren(AppPProjectIdRouteRouteChildren)

interface AppRouteRouteChildren {
  AppEquipoRouteRoute: typeof AppEquipoRouteRouteWithChildren
  AppAdminRoute: typeof AppAdminRoute
  AppArchivadosRoute: typeof AppArchivadosRoute
  AppBandejaRoute: typeof AppBandejaRoute
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppCamposPersonalizadosRoute: typeof AppCamposPersonalizadosRoute
  AppCompartirRoute: typeof AppCompartirRoute
  AppEspaciosRoute: typeof AppEspaciosRoute
  AppMembersRoute: typeof AppMembersRoute
  AppMisTareasRoute: typeof AppMisTareasRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPlantillasRoute: typeof AppPlantillasRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportesRoute: typeof AppReportesRoute
  AppTablaRoute: typeof AppTablaRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPProjectIdRouteRoute: typeof AppPProjectIdRouteRouteWithChildren
  AppFFolderIdRoute: typeof AppFFolderIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppEquipoRouteRoute: AppEquipoRouteRouteWithChildren,
  AppAdminRoute: AppAdminRoute,
  AppArchivadosRoute: AppArchivadosRoute,
  AppBandejaRoute: AppBandejaRoute,
  AppCalendarioRoute: AppCalendarioRoute,
  AppCamposPersonalizadosRoute: AppCamposPersonalizadosRoute,
  AppCompartirRoute: AppCompartirRoute,
  AppEspaciosRoute: AppEspaciosRoute,
  AppMembersRoute: AppMembersRoute,
  AppMisTareasRoute: AppMisTareasRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPlantillasRoute: AppPlantillasRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportesRoute: AppReportesRoute,
  AppTablaRoute: AppTablaRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppIndexRoute: AppIndexRoute,
  AppPProjectIdRouteRoute: AppPProjectIdRouteRouteWithChildren,
  AppFFolderIdRoute: AppFFolderIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  EnlaceTokenRoute: EnlaceTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
